[build]
builder = "nixpacks"
buildCommand = "cd activity-detail && npm install && npm run build && cd .."

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
